all:
	g++-5 -std=c++11 -I ./ -I ${LCIO}/include/  -L ${LCIO}/lib/ -l lcio -lsio -shared -fPIC -o ../test.dylib lcevt.cc lcrdr.cc lccol.cc lcmcp.cc lcclu.cc lccah.cc lcrcp.cc lcsch.cc lcrel.cc lcsth.cc
