function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(LCIO.__init__)})
    precompile(Tuple{typeof(LCIO.close), CxxWrap.CxxWrapCore.CxxPtr{LCIO.LCWriter}})
    precompile(Tuple{typeof(LCIO.createLCWriter)})
    precompile(Tuple{typeof(LCIO.getCollection), CxxWrap.CxxWrapCore.CxxPtr{LCIO.LCEvent}, String})
    precompile(Tuple{typeof(LCIO.getCollection), LCIO.LCEventImplAllocated, String})
    precompile(Tuple{typeof(LCIO.getEnergy), CxxWrap.CxxWrapCore.CxxPtr{LCIO.MCParticle}})
    precompile(Tuple{typeof(LCIO.getMomentum), CxxWrap.CxxWrapCore.CxxPtr{LCIO.MCParticle}})
    precompile(Tuple{typeof(LCIO.getNumberOfElements), LCIO.TypedCollectionAllocated{LCIO.SimCalorimeterHit}})
    precompile(Tuple{typeof(LCIO.getNumberOfEvents), LCIO._LCStdHepRdrCppAllocated})
    precompile(Tuple{typeof(LCIO.getPDG), CxxWrap.CxxWrapCore.CxxPtr{LCIO.MCParticle}})
    precompile(Tuple{typeof(LCIO.getParents), CxxWrap.CxxWrapCore.CxxPtr{LCIO.MCParticle}})
    precompile(Tuple{typeof(LCIO.getTypeName), LCIO.TypedCollectionAllocated{LCIO.SimCalorimeterHit}})
    precompile(Tuple{typeof(LCIO.open), CxxWrap.CxxWrapCore.CxxPtr{LCIO.LCWriter}, String, Int64})
    precompile(Tuple{typeof(LCIO.parameters), LCIO.LCRunHeaderImplAllocated})
    precompile(Tuple{typeof(LCIO.readNextEvent), LCIO.LCStdHepRdr})
    precompile(Tuple{typeof(LCIO.removeCollection), LCIO.LCEventImplAllocated, String})
    precompile(Tuple{typeof(LCIO.setPDG), LCIO.MCParticleImplAllocated, Int64})
    precompile(Tuple{typeof(LCIO.setRunNumber), LCIO.LCRunHeaderImplAllocated, Int64})
    precompile(Tuple{typeof(LCIO.setValue), CxxWrap.CxxWrapCore.CxxRef{LCIO.LCParameters}, String, Float32})
    precompile(Tuple{typeof(LCIO.setValue), CxxWrap.CxxWrapCore.CxxRef{LCIO.LCParameters}, String, Int64})
    precompile(Tuple{typeof(LCIO.setValue), CxxWrap.CxxWrapCore.CxxRef{LCIO.LCParameters}, String, String})
    precompile(Tuple{typeof(LCIO.updateNextEvent), LCIO._LCStdHepRdrCppAllocated, LCIO.LCEventImplAllocated, String})
    precompile(Tuple{typeof(LCIO.writeEvent), CxxWrap.CxxWrapCore.CxxPtr{LCIO.LCWriter}, LCIO.LCEventImplAllocated})
    precompile(Tuple{typeof(LCIO.writeRunHeader), CxxWrap.CxxWrapCore.CxxPtr{LCIO.LCWriter}, LCIO.LCRunHeaderImplAllocated})
end
